version: '3.8'

services:
  python-app:
    build: .
    container_name: python-app
    volumes:
      - .:/app
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/SA-michael.json
    command: python src/main.py
